# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7f2DjYIhN4f_AJaAY-2JwEF5LFdh83r
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

df = pd.read_csv('simulated_bridge_data.csv')
df

# Initial data overview
print(df.head())
print(df.info())
print(df.describe())

# 1.1 Handle missing values
from sklearn.impute import SimpleImputer  # Import the missing value imputer

# Handle missing values
imputer = SimpleImputer(strategy='most_frequent')  # or 'mean' for numeric values
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed

# 1.2 Encode categorical columns
from sklearn.preprocessing import LabelEncoder  # Import LabelEncoder

# Encode categorical columns
categorical_cols = df_imputed.select_dtypes(include=['object']).columns
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df_imputed[col] = le.fit_transform(df_imputed[col])
    label_encoders[col] = le  # Store encoder for inverse transformation if needed

categorical_cols

# 1.3 Feature-target split
target_col=[ 'Deterioration_Condition']
feature_cols =['Bridge_Age', 'Average_Daily_Traffic', 'Weather_Condition',
       'Bridge_Material', 'Bridge_Width',
       'Length (m)', 'Height (m)']
X = df_imputed[feature_cols]
y = df_imputed[target_col]

# 1.4 Scaling features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

#Exploratory Data Analysis (EDA)
# Class distribution
sns.countplot(x=y['Deterioration_Condition'])
plt.title("Bridge Deterioration Level Distribution")
plt.show()

# Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(df_imputed.corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Step 3: KNN Model Training
# --------------------------

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Train KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)



# Predict and evaluate
y_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
plt.figure(figsize=(6,6))
sns.scatterplot(x=y_test.values.ravel(), y=y_pred.ravel(), color='dodgerblue')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')  # Perfect line
plt.xlabel('Actual Deterioration Condition')
plt.ylabel('Predicted Deterioration Condition')
plt.title('Actual vs Predicted - KNN Regressor')
plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(6,4))

sns.scatterplot(
    x=y_pred.ravel(),
    y=residuals.values.ravel(),   # <-- convert to numpy array first
    color='orange'
)


plt.axhline(0, color='black', linestyle='--')
plt.xlabel('Predicted Deterioration Condition')
plt.ylabel('Residuals')
plt.show()

#hypertuning
from sklearn.model_selection import GridSearchCV

param_grid = {'n_neighbors': range(1, 21)}
grid = GridSearchCV(KNeighborsRegressor(), param_grid, cv=5, scoring='r2')
grid.fit(X_train, y_train)

print("Best K:", grid.best_params_)
print("Best R2:", grid.best_score_)

import matplotlib.pyplot as plt
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score

k_range = range(1, 21)
r2_scores = []

# Performing cross-validation for each k and storing mean R2 score
for k in k_range:
    knn = KNeighborsRegressor(n_neighbors=k)
    scores = cross_val_score(knn, X_train, y_train, cv=5, scoring='r2')
    r2_scores.append(scores.mean())

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(k_range, r2_scores, marker='o', linestyle='-', color='b', label='R² Score')
plt.axvline(x=8, color='r', linestyle='--', label='Optimal k=8')
plt.scatter(8, r2_scores[7], color='red', s=100, label=f'Best R²={r2_scores[7]:.4f}')

plt.title('Effect of k on KNN Regressor Performance')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('R² Score')
plt.xticks(k_range)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot 1: Histogram - Deterioration Condition Distribution
plt.figure(figsize=(8, 5))
sns.histplot(df['Deterioration_Condition'], kde=True, bins=20)
plt.title('Distribution of Deterioration Condition')
plt.show()

# Plot 2: Boxplot - Material vs Deterioration
plt.figure(figsize=(8, 5))
sns.boxplot(x='Bridge_Material', y='Deterioration_Condition', data=df)
plt.title('Material wise Deterioration Condition')
plt.xticks(rotation=45)
plt.show()

# Plot 4: Scatterplot - Age vs Deterioration
plt.figure(figsize=(8, 5))
sns.scatterplot(x='Bridge_Age', y='Deterioration_Condition', data=df)
plt.title('Bridge Age vs Deterioration Condition')
plt.show()

# Plot 5: Scatterplot - Traffic vs Deterioration
plt.figure(figsize=(8, 5))
sns.scatterplot(x='Average_Daily_Traffic', y='Deterioration_Condition', data=df)
plt.title('Traffic vs Deterioration Condition')
plt.show()

# Plot 9: Pairplot - Relationships
selected_features = ['Bridge_Age', 'Average_Daily_Traffic', 'Bridge_Width', 'Deterioration_Condition']
sns.pairplot(df[selected_features])
plt.show()

# Feature Importance via Permutation
from sklearn.inspection import permutation_importance
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = df.drop('Deterioration_Condition', axis=1).select_dtypes(include=[np.number])
y = df['Deterioration_Condition']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = KNeighborsRegressor()
model.fit(X_train, y_train)

result = permutation_importance(model, X_test, y_test, n_repeats=10, random_state=42)

importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': result.importances_mean})
importance_df.sort_values(by='Importance', ascending=False, inplace=True)

plt.figure(figsize=(8, 5))
sns.barplot(x='Importance', y='Feature', data=importance_df)
plt.title('Feature Importance (KNN Permutation)')
plt.show()

#random forest
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Create and Train the Random Forest Model
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

# Predict on Test Data
y_pred_rf = rf.predict(X_test)

# Evaluation Metrics
r2_rf = r2_score(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print("Random Forest Regressor Performance:")
print("R² Score      :", r2_rf)
print("MAE           :", mae_rf)
print("RMSE          :", rmse_rf)

import matplotlib.pyplot as plt
import seaborn as sns

# Predicting on Test Data
y_pred_rf = rf.predict(X_test)

plt.figure(figsize=(7,5))
sns.scatterplot(x=y_test.values.ravel(), y=y_pred_rf.ravel(), color='teal', s=50)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

plt.xlabel("Actual Deterioration Condition")
plt.ylabel("Predicted Deterioration Condition")
plt.title("Random Forest Regressor: Actual vs Predicted")
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd

feature_importance = pd.Series(rf.feature_importances_, index=X.columns)
feature_importance.sort_values(ascending=True).plot(kind='barh', figsize=(8,5), color='purple')

plt.xlabel('Feature Importance Score')
plt.title('Feature Importance in Random Forest Regressor')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Performance Metrics
models = ['KNN Regressor', 'Random Forest']
r2_scores = [0.7504, 0.8257]
mae_scores = [0.52, 0.47]
rmse_scores = [0.68, 0.61]

x = np.arange(len(models))  # label locations
width = 0.25  # width of the bars

fig, ax = plt.subplots(figsize=(8, 5))
rects1 = ax.bar(x - width, r2_scores, width, label='R² Score',color='indigo')
rects2 = ax.bar(x, mae_scores, width, label='MAE',color='turquoise')
rects3 = ax.bar(x + width, rmse_scores, width, label='RMSE',color='lightblue')

# Labels & Titles
ax.set_ylabel('Scores')
ax.set_title('Comparison of KNN and Random Forest Regressor')
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.legend()

plt.tight_layout()
plt.show()

import nltk
import numpy as np
import networkx as nx
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample text
text = """
Fahrenheit 451 is a dystopian novel by Ray Bradbury that explores a future society where books are banned and 'firemen' burn any that are found.
The story follows Guy Montag, a fireman who becomes disillusioned with his role in suppressing knowledge and begins to rebel against the system.
Montag encounters Clarisse, a young woman who opens his eyes to the beauty of the world and the value of independent thought.
As he begins to read forbidden books, Montag’s perspective shifts, putting him in conflict with the oppressive government.
The novel delves into themes of censorship, conformity, and the transformative power of literature.
"""

nltk.download('punkt')

nltk.download('stopwords')

sentences = sent_tokenize(text)
print(sentences)